package com.project.fleem.models

import com.project.fleem.R


object FilmData {
    val dummyFilms = listOf(
        Film(1,
            R.drawable.se7en,
            "Se7en",
            "\"Se7en\" adalah film thriller psikologis yang mengikuti perjalanan dua detektif yang berusaha mengejar pembunuh berantai yang sadis dan cerdas. Di kota yang penuh korupsi dan kebusukan, detektif veteran David Mills (diperankan oleh Brad Pitt) dipasangkan dengan detektif yang lebih berpengalaman William Somerset (diperankan oleh Morgan Freeman) untuk memecahkan serangkaian pembunuhan mengerikan yang terinspirasi dari tujuh dosa maut.\n",
            200000),
        Film(2,
            R.drawable.theprestige,
            "The Prestige",
            "\"The Prestige\" adalah sebuah film thriller psikologis yang disutradarai oleh Christopher Nolan. Film ini menggambarkan persaingan sengit antara dua pesulap terkenal, Robert Angier (Hugh Jackman) dan Alfred Borden (Christian Bale), di London pada akhir abad ke-19. Dalam upaya mereka untuk menciptakan trik sulap terbaik, persaingan mereka berubah menjadi obsesi dan kebencian yang saling mempengaruhi kehidupan pribadi mereka. Masing-masing pesulap menggunakan segala cara untuk mengungguli yang lain, termasuk mencuri trik rahasia satu sama lain.\n",
            30000),
        Film(3,
            R.drawable.thepianist,
            "The Pianist",
            "\"The Pianist\" adalah sebuah film drama sejarah yang dirilis pada tahun 2002. Film ini disutradarai oleh Roman Polanski dan diadaptasi dari buku memoar yang ditulis oleh Władysław Szpilman. Cerita film ini berlatar belakang Perang Dunia II dan mengisahkan kisah nyata seorang pianis Polandia Yahudi bernama Władysław Szpilman. Pada masa pendudukan Jerman di Warsawa, Polandia, Szpilman dihadapkan pada kengerian dan penderitaan yang ditimbulkan oleh Holocaust. Dia melihat teman-temannya dan keluarganya dibunuh atau ditangkap oleh pasukan Nazi. Szpilman berhasil lolos dari penangkapan dan menghindari eksekusi berkat bantuan beberapa orang yang berani.\n",
            150000),
        Film(4,
            R.drawable.savingprivateryan,
            "Saving Private Ryan",
            "\"Saving Private Ryan\" adalah sebuah film perang epik yang disutradarai oleh Steven Spielberg. Film ini berlatar belakang Perang Dunia II dan mengikuti misi sekelompok prajurit Amerika Serikat yang dikirim untuk mencari dan menyelamatkan seorang prajurit bernama James Ryan. James Ryan adalah satu-satunya anak laki-laki dari empat bersaudara yang masih hidup setelah tiga saudaranya tewas dalam pertempuran yang berbeda-beda.\n",
            35000),
        Film(5,
            R.drawable.sevensamurai,
            "Seven Samurai",
            "\"Seven Samurai\" adalah sebuah film Jepang yang dirilis pada tahun 1954, disutradarai oleh Akira Kurosawa. Film ini mengambil latar belakang di Jepang pada abad ke-16, di mana tujuh samurai yang berbeda latar belakang dan kepribadian disewa oleh sebuah desa untuk melindungi mereka dari serangan sekelompok perampok yang kuat. Para samurai ini membentuk sebuah tim yang tidak lazim, masing-masing dengan keahlian unik mereka, seperti kepemimpinan, kecepatan, ketangkasan, dan keahlian bela diri. Mereka melakukan persiapan, melatih penduduk desa dalam pertahanan, dan mengembangkan strategi untuk menghadapi serangan yang akan datang.\n",
            250000),
        Film(6,
            R.drawable.goodfellas,
            "Goodfellas",
            "\"Goodfellas\" adalah sebuah film drama kejahatan yang dirilis pada tahun 1990. Disutradarai oleh Martin Scorsese, film ini didasarkan pada buku non-fiksi berjudul \"Wiseguy\" karya Nicholas Pileggi. Cerita film ini mengikuti perjalanan hidup seorang gangster bernama Henry Hill, yang diperankan oleh Ray Liotta. Goodfellas menggambarkan kehidupan Henry Hill sejak masa kecilnya yang terjerat dalam dunia kejahatan di lingkungan Brooklyn, New York. Dia menjadi anggota dalam kelompok mafia Italia yang kuat dan terkenal, serta memiliki hubungan erat dengan rekan-rekannya, termasuk Jimmy Conway (diperankan oleh Robert De Niro) dan Tommy DeVito (diperankan oleh Joe Pesci).\n",
            180000),
        Film(7,
            R.drawable.thematrixposter,
            "The Matrix",
            "\"The Matrix\" adalah film aksi ilmiah yang dirilis pada tahun 1999 dan disutradarai oleh The Wachowski Brothers. Cerita film ini berpusat pada karakter bernama Neo (diperankan oleh Keanu Reeves), seorang hacker komputer yang menemukan keberadaan dunia maya yang disebut \"Matrix\". Matrix adalah simulasi komputer canggih yang mengekang umat manusia, membuat mereka hidup dalam ilusi yang mirip dengan dunia nyata.\n",
            80000),
        Film(8,
            R.drawable.thedarkknight,
            "The Dark Knight",
            "\"The Dark Knight\" adalah sebuah film superhero yang dirilis pada tahun 2008 dan merupakan bagian dari trilogi Batman karya Christopher Nolan. Film ini mengisahkan perjuangan Batman (diperankan oleh Christian Bale) dalam melawan kejahatan yang mengancam kota Gotham City. Ketika seorang penjahat psikopat bernama Joker (diperankan oleh Heath Ledger) muncul dan menimbulkan kekacauan di seluruh kota, Batman berusaha untuk menghentikannya dengan bantuan dari Letnan James Gordon (diperankan oleh Gary Oldman) dan Jaksa Harvey Dent (diperankan oleh Aaron Eckhart). Dalam perjalanan menghadapi Joker, Batman harus menghadapi pertarungan moral yang sulit dan menghadapi konsekuensi dari tindakan-tindakan pahlawannya. \"\n",
            90000),
        Film(9,
            R.drawable.thegodfather,
            "The Godfather",
            "\"The Godfather\" adalah sebuah film klasik yang dirilis pada tahun 1972 dan dianggap sebagai salah satu film terbesar dalam sejarah perfilman. Disutradarai oleh Francis Ford Coppola, film ini berdasarkan novel dengan judul yang sama karya Mario Puzo. The Godfather mengisahkan kisah keluarga mafia Italia-Amerika yang berpusat di sekitar Don Vito Corleone, diperankan oleh Marlon Brando. Don Vito adalah seorang pemimpin mafia yang memiliki kekuasaan dan pengaruh besar di New York City. Film ini menggambarkan kehidupan keluarga Corleone, termasuk perjuangan untuk mempertahankan kekuasaan dan keluarga mereka. \n",
            300000),
        Film(10,
            R.drawable.joker,
            "Joker",
            "\"Joker\" adalah sebuah film drama psikologis yang dirilis pada tahun 2019. Film ini disutradarai oleh Todd Phillips dan dibintangi oleh Joaquin Phoenix sebagai karakter utama, Arthur Fleck/Joker. Cerita film ini menggambarkan perjalanan Arthur Fleck dari seorang pria yang terpinggirkan dan diabaikan dalam masyarakat Gotham City yang korup, hingga menjadi salah satu penjahat paling ikonik dalam sejarah. Melalui narasi yang gelap dan intens, penonton dibawa untuk menyaksikan perubahan yang mengerikan dalam diri Arthur, yang terinspirasi oleh berbagai peristiwa traumatis dan perlakuan tidak adil yang dialaminya. \"Joker\" merupakan sebuah eksplorasi mendalam mengenai kehancuran mental dan kegilaan, serta bagaimana ketidakadilan sosial dan kurangnya empati dapat membentuk seseorang menjadi monster yang tak terelakkan.\n",
            120000),
    )
}